name: Juice Shop (Docker run)

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]

jobs:
  run-juice:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Start Juice Shop container
        run: |
          docker pull bkimminich/juice-shop:latest
          docker run -d --name juice -p 3000:3000 bkimminich/juice-shop:latest
          echo "Container ID:"
          docker ps --filter "name=juice" --format "table {{.ID}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"

      - name: Wait until Juice Shop is up
        shell: bash
        run: |
          for i in {1..120}; do   # ~4 λεπτά max
            if curl -fsS http://localhost:3000/ >/dev/null; then
              echo "✅ Juice Shop is up!"
              exit 0
            fi
            if ! docker ps --format '{{.Names}}' | grep -q '^juice$'; then
              echo "❌ Container exited unexpectedly"
              docker logs juice || true
              exit 1
            fi
            echo "⏳ Waiting..."
            sleep 2
          done
          echo "❌ Timeout while waiting for Juice Shop"
          docker logs juice || true
          exit 1

      - name: Smoke test homepage
        run: |
          curl -fsS http://localhost:3000/ -o homepage.html
          head -n 15 homepage.html || true

      - name: Upload homepage artifact
        uses: actions/upload-artifact@v4
        with:
          name: juice-shop-homepage
          path: homepage.html

      - name: Show container logs (always)
        if: always()
        run: docker logs juice || true

      - name: Cleanup container (always)
        if: always()
        run: docker rm -f juice || true
